input:
  file: 
    name: "core-public-organisation-ap.ttl"
    format: "ttl"
  repository:
    - name: "Lov"
      endpoint: "http://localhost:7200/repositories/lov"
  api:
    altervista: 
      endpoint: "http://thesaurus.altervista.org/thesaurus/v1"
      key: "Kdnuiqz85LO7gGIHdGZf"
alternative: "skosxl"
skosxl:
  baseuri: "http://example.com/label/"
output:
  file: 
    name: "cpov-synonyms-skosxl2.ttl"
    format: "ttl"
