input:
  file: 
    name: "core-business-ap.ttl"
    format: "ttl"
  mapping:
    dcschema: "http://localhost:7200/repositories/mapping-dc-schema"
    wdschema: "http://localhost:7200/repositories/mapping-wd-schema"
    dbpedia: "https://dbpedia.org/sparql"
    wikidata: "https://query.wikidata.org/sparql"
    lov: "http://localhost:7200/repositories/lov"
output:
  file: 
    name: "business-indirect-mapping.ttl"
    format: "ttl"
